package views.MuonTraFrame;

import Bean.MuonTraBean;
import ControllersAddNewController.AddCoSoVatChatPhongBanController;
import ControllersAddNewController.AddNewController;
import controllers.LoginController;
import controllers.MuonTraPanelController;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.EventObject;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.PhongBanModel;
import models.CoSoVatChatModel;
import models.NguoiMuonModel;
import models.ThoiGianModel;
import utility.ClassTableModel;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionEvent;
import java.awt.Toolkit;
import javax.swing.border.LineBorder;
import com.toedter.calendar.JDateChooser;

import java.awt.Rectangle;

/**
 *
 * @author Hai
 */
public class DangKySuDungFrame extends javax.swing.JFrame {


    /**
     * @wbp.parser.constructor
     */
    public DangKySuDungFrame(MuonTraPanelController parentController, JFrame parentJFrame) {
    	setBackground(new Color(255, 228, 228));
    	this.parentController = parentController;
    	this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(true);
        initComponents();
        controller = new MuonCoSoVatChatPhongBanFrame(tablePanel, this.parentFrame);
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 566, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 211, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        controller.setDataTable();
    	setIconImage(Toolkit.getDefaultToolkit().getImage(DangKySuDungFrame.class.getResource("/Icons/house.png")));
    	setTitle("Đăng ký sử dụng cơ sở vật chất / phòng ban");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    public DangKySuDungFrame(JFrame parentJFrame) {
        this.parentController = new MuonTraPanelController(){
            @Override
            public void refreshData() {
                // do nothing
            }

            @Override
            public void initAction() {
                // do nothing
            }
            
            
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.muonTraBeann = new MuonTraBean();
        initComponents();
        setTitle("Thêm mới đối tượng đăng ký sử dụng cơ sở vật chất");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        childController = new AddNewController();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	DangKyCoSoVatChatPanel = new JPanel();
    	DangKyCoSoVatChatPanel.setBackground(new Color(255, 228, 228));
    	getContentPane().add(DangKyCoSoVatChatPanel, BorderLayout.CENTER);
    	
    	JLabel tenDangKyJlb = new JLabel("Tên người đăng ký:");
    	tenDangKyJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	tenNguoiMuonJtf = new JTextField();
    	tenNguoiMuonJtf.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	tenNguoiMuonJtf.setColumns(10);
    	
    	JLabel idJlb = new JLabel("CCCD/TCC/HC:");
    	idJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	idJtf = new JTextField();
    	idJtf.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	idJtf.setColumns(10);
    	
    	JLabel lienHeJlb = new JLabel("Liên hệ:");
    	lienHeJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	lienHeJtf = new JTextField();
    	lienHeJtf.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	lienHeJtf.setColumns(10);
    	
    	lblNewLabel_1_2 = new JLabel("Thời gian mượn:");
    	lblNewLabel_1_2.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	lblNewLabel_1_3 = new JLabel("Thời gian trả:");
    	lblNewLabel_1_3.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JButton okButton = new JButton("OK");
    	okButton.setBorder(null);
    	okButton.addMouseListener(new MouseAdapter() {
    		@Override
        	public void mouseEntered(MouseEvent e) {
                okButton.setBackground(new Color(195, 66, 2));
        	}
    		@Override
        	public void mousePressed(MouseEvent e) {
            	okButton.setBackground(new Color(212, 84, 21));
        	}
    		@Override
        	public void mouseReleased(MouseEvent e) {
                okButton.setBackground(new Color(195, 66, 2));
        	}
    		@Override
        	public void mouseExited(MouseEvent e) {
            	okButton.setBackground(new Color(212, 84, 21));
        	}
    	});
    	okButton.setForeground(Color.WHITE);
    	okButton.setFont(new Font("Tahoma", Font.BOLD, 16));
    	okButton.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent evt) {
    			addThongTinDangKyCoSoVatChatActionPerformed(evt);
    		}
    		
    	});
    	okButton.setBackground(new Color(212, 84, 21));
    	
    	tablePanel = new JPanel();
    	tablePanel.setBackground(new Color(255, 228, 228));
    	
    	muonButton = new JButton("Mượn");
    	muonButton.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	muonButton.setBackground(new Color(0, 255, 0));
    	muonButton.setBorder(null);
    	muonButton.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent evt) {
    			muonActionPerformed(evt);
    		}
    	});
    	muonButton.setIcon(null);
    	
    	ngayMuonJdc = new JDateChooser();
    	
    	ngayTraJdc = new JDateChooser();
    	GroupLayout gl_DangKyCoSoVatChatPanel = new GroupLayout(DangKyCoSoVatChatPanel);
    	gl_DangKyCoSoVatChatPanel.setHorizontalGroup(
    		gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addContainerGap()
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addComponent(lienHeJlb, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
    					.addComponent(idJlb, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
    					.addComponent(lblNewLabel_1_2, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
    					.addComponent(tenDangKyJlb)
    					.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING)
    						.addComponent(muonButton, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
    						.addComponent(lblNewLabel_1_3, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)))
    				.addGap(13)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING, false)
    							.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    								.addComponent(idJtf, GroupLayout.PREFERRED_SIZE, 293, GroupLayout.PREFERRED_SIZE)
    								.addGap(20))
    							.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    								.addComponent(tenNguoiMuonJtf)
    								.addGap(18)))
    						.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
    					.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING, false)
    						.addComponent(ngayMuonJdc, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    						.addComponent(lienHeJtf, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
    					.addComponent(ngayTraJdc, GroupLayout.PREFERRED_SIZE, 293, GroupLayout.PREFERRED_SIZE)
    					.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, 294, GroupLayout.PREFERRED_SIZE))
    				.addContainerGap(17, Short.MAX_VALUE))
    	);
    	gl_DangKyCoSoVatChatPanel.setVerticalGroup(
    		gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addContainerGap()
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    							.addComponent(tenDangKyJlb)
    							.addComponent(tenNguoiMuonJtf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    							.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    								.addGap(13)
    								.addComponent(idJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    								.addGap(20)
    								.addComponent(lienHeJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    								.addGap(16)
    								.addComponent(lblNewLabel_1_2, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
    							.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    								.addGap(47)
    								.addComponent(lienHeJtf, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
    								.addGap(10)
    								.addComponent(ngayMuonJdc, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))))
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addGap(31)
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    							.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
    							.addComponent(idJtf, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))))
    				.addPreferredGap(ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addComponent(lblNewLabel_1_3, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    					.addComponent(ngayTraJdc, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
    				.addGap(11)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING)
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addComponent(muonButton, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
    						.addGap(58))
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
    						.addContainerGap())))
    	);
    	DangKyCoSoVatChatPanel.setLayout(gl_DangKyCoSoVatChatPanel);
    	pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void muonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
    	controller.setMuonCoSoVatChatPhongBanFrame();
    	controller.setLocationRelativeTo(null);
    	controller.setResizable(false);
    	controller.setVisible(true);
    }
    private void addThongTinDangKyCoSoVatChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
    	if(validateValueInForm()) {
    		NguoiMuonModel nguoiMuonModel = this.muonTraBeann.getNguoiMuonModel();
    		ThoiGianModel thoiGianModel = this.muonTraBeann.getThoiGianModel();
    		List<CoSoVatChatModel> listCoSoVatChatModels = this.controller.getCoSoVatChatMuon();
    		List<PhongBanModel> listPhongBanModels = this.controller.getPhongBanMuon();
    		nguoiMuonModel.setTenNguoiMuon(tenNguoiMuonJtf.getText());
    		nguoiMuonModel.setCccd(idJtf.getText());
    		nguoiMuonModel.setLienHe(lienHeJtf.getText());
    		thoiGianModel.setThoiGianMuon(ngayMuonJdc.getDate());
    		thoiGianModel.setThoiGianTra(ngayTraJdc.getDate());
    		this.muonTraBeann.setListCoSoVatChatModels(listCoSoVatChatModels);
    		this.muonTraBeann.setListPhongBanModels(listPhongBanModels);
    		this.muonTraBeann.setNguoiMuonModel(nguoiMuonModel);
    		this.muonTraBeann.setThoiGianModel(thoiGianModel);
    		
            try {
                if(this.childController.addNewNguoiMuon(muonTraBeann)) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công!!");
                    close();
                    parentController.refreshData();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
    	}
    }
    // check cac gia tri duoc nhap vao form
    private boolean validateValueInForm() {
        // check null
    	if(tenNguoiMuonJtf.getText().trim().isEmpty()
    			|| lienHeJtf.getText().trim().isEmpty()
    			) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập hết các trường bắt buộc", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
    	}
        if (idJtf.getText().length() != 9 && idJtf.getText().length() != 12) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng CCCD/CC/HC", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        Date now = new Date();
        if(now.compareTo(ngayMuonJdc.getDate()) > 0) {
            JOptionPane.showMessageDialog(rootPane, "Ngày mượn phải được mượn hiện tại hoặc tương lai!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(ngayMuonJdc.getDate().compareTo(ngayMuonJdc.getDate()) > 0) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng ngày trả", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    private MuonCoSoVatChatPhongBanFrame controller;
	private MuonTraPanelController parentController;
    private JFrame parentFrame;
    private MuonTraBean muonTraBeann;
    private AddNewController childController;
    private JPanel DangKyCoSoVatChatPanel;
    private JTextField tenNguoiMuonJtf;
    private JTextField idJtf;
    private JTextField lienHeJtf;
    private JLabel lblNewLabel_1_2;
    private JLabel lblNewLabel_1_3;
    private JButton muonButton;
    private JDateChooser ngayMuonJdc;
    private JDateChooser ngayTraJdc;
    private ClassTableModel classTableModel = null;
    private JPanel tablePanel;
}
