package views.MuonTraFrame;

import Bean.CoSoVatChatBean;
import Bean.MuonTraBean;
import ControllersAddNewController.AddNewController;
import controllers.CoSoVatChatPanelController;
import controllers.LoginController;
import controllers.MuonTraPanelController;
import controllers.MuonTraController.XemChiTietMuonTraCotroller;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Timestamp;
import java.util.Date;
import java.util.EventObject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.PhongBanModel;
import models.CoSoVatChatModel;
import models.NguoiMuonModel;
import models.NhaTaiTroModel;
import models.ThoiGianModel;
import services.MuonTraService;
import services.TimeService;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionEvent;
import java.awt.Toolkit;
import javax.swing.border.LineBorder;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author Hai
 */
public class HoanTraFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPeopleJFrame
     */



//    public AddNewPeopleJFrame() {
//        initComponents();
//        setTitle("Thêm mới nhân khẩu");
//        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        controller = new AddNewController();
//    }

    /**
     * @wbp.parser.constructor
     */
    public HoanTraFrame(XemChiTietMuonTraCotroller parentController, JFrame parentJFrame, String tenNguoiMuon, String cccdNguoiMuon, String thoiGianMuon, String tenCoSoVatChatPhongBan, int soLuongMuon, int isCoSoVatChat) {
    	setBackground(new Color(255, 228, 228));
    	this.parentController = parentController;
    	this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.muonTraBean = new MuonTraBean();
        initComponents();
        this.tenCoSoVatChatPhongBanDetailJlb.setText(tenCoSoVatChatPhongBan);
        this.soLuongTraJtf.setText(soLuongMuon+"");
        this.cccdNguoiMuon = cccdNguoiMuon;
        this.thoiGianMuon = thoiGianMuon;
        this.tenNguoiMuon = tenNguoiMuon;
    	setIconImage(Toolkit.getDefaultToolkit().getImage(HoanTraFrame.class.getResource("/Icons/house.png")));
    	setTitle("Hoàn trả cơ sở vật chất / phòng ban");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
        controller = new AddNewController();
    }
    
    public HoanTraFrame(JFrame parentJFrame) {
        this.parentController = new XemChiTietMuonTraCotroller(){
            @Override
            public void refreshData() {
                // do nothing
            }

            @Override
            public void initAction() {
                // do nothing
            }
            
            
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.muonTraBean = new MuonTraBean();
        initComponents();
        setTitle("Thêm mới cơ sở vật chất");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new AddNewController();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	DangKyCoSoVatChatPanel = new JPanel();
    	DangKyCoSoVatChatPanel.setBackground(new Color(255, 228, 228));
    	getContentPane().add(DangKyCoSoVatChatPanel, BorderLayout.CENTER);
    	
    	JLabel tenCoSoVatChatPhongBanJlb = new JLabel("Tên cơ sở vật chất / phòng ban:");
    	tenCoSoVatChatPhongBanJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JLabel soLuongMuonJlb = new JLabel("Số lượng mượn:");
    	soLuongMuonJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	soLuongTraJtf = new JTextField();
    	soLuongTraJtf.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	soLuongTraJtf.setColumns(10);
    	
    	JButton okButton = new JButton("OK");
    	okButton.addMouseListener(new MouseAdapter() {
    		
    		@Override
        	public void mouseEntered(MouseEvent e) {
                okButton.setBackground(new Color(195, 66, 2));
        	}
    		@Override
        	public void mousePressed(MouseEvent e) {
            	okButton.setBackground(new Color(212, 84, 21));
        	}
    		@Override
        	public void mouseReleased(MouseEvent e) {
                okButton.setBackground(new Color(195, 66, 2));
        	}
    		@Override
        	public void mouseExited(MouseEvent e) {
            	okButton.setBackground(new Color(212, 84, 21));
        	}
    	});
    	okButton.setBorder(null);
    	okButton.setForeground(Color.WHITE);
    	okButton.setFont(new Font("Tahoma", Font.BOLD, 16));
    	okButton.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent evt) {
    			addThongTinDangKyCoSoVatChatActionPerformed(evt);
    		}
    	});
    	okButton.setBackground(new Color(212, 84, 21));
    	
    	tenCoSoVatChatPhongBanDetailJlb = new JLabel("null");
    	tenCoSoVatChatPhongBanDetailJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JLabel soLuongTraJlb = new JLabel("Số lượng trả: ");
    	soLuongTraJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	soLuongMuonDetailJlb = new JLabel("0");
    	soLuongMuonDetailJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	GroupLayout gl_DangKyCoSoVatChatPanel = new GroupLayout(DangKyCoSoVatChatPanel);
    	gl_DangKyCoSoVatChatPanel.setHorizontalGroup(
    		gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addContainerGap()
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addComponent(tenCoSoVatChatPhongBanJlb)
    					.addComponent(soLuongMuonJlb, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
    					.addComponent(soLuongTraJlb, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
    				.addPreferredGap(ComponentPlacement.UNRELATED)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING)
    					.addGroup(Alignment.LEADING, gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addComponent(tenCoSoVatChatPhongBanDetailJlb)
    						.addGap(140))
    					.addComponent(soLuongMuonDetailJlb, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
    					.addGroup(Alignment.LEADING, gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addComponent(soLuongTraJtf, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
    						.addPreferredGap(ComponentPlacement.RELATED)))
    				.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
    				.addContainerGap())
    	);
    	gl_DangKyCoSoVatChatPanel.setVerticalGroup(
    		gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING)
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addGap(84)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    					.addComponent(tenCoSoVatChatPhongBanJlb)
    					.addComponent(tenCoSoVatChatPhongBanDetailJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
    				.addGap(18)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addComponent(soLuongMuonJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    					.addComponent(soLuongMuonDetailJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
    				.addGap(18)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    					.addComponent(soLuongTraJtf, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
    					.addComponent(soLuongTraJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
    				.addContainerGap(58, Short.MAX_VALUE))
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addContainerGap(97, Short.MAX_VALUE)
    				.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
    				.addGap(91))
    	);
    	
    	DangKyCoSoVatChatPanel.setLayout(gl_DangKyCoSoVatChatPanel);
    	pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addThongTinDangKyCoSoVatChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
    	if(validateValueInForm()) {
    		MuonTraService muonTraService = new MuonTraService();
    		TimeService timeService = new TimeService();
    		int soLuongMuon = Integer.parseInt(soLuongMuonDetailJlb.getText());
    		int soLuongTra = Integer.parseInt(soLuongTraJtf.getText());
    		String tenCoSoVatChatPhongBan = tenCoSoVatChatPhongBanDetailJlb.getText();
    		Timestamp thoiGianMuonTS = timeService.convertDatetableToTimestamp(this.thoiGianMuon);
    		String thoiGianMuon = timeService.convertToDate(thoiGianMuonTS);
    		if(isCoSoVatChat > 0) {
    			CoSoVatChatModel coSoVatChatModel = muonTraBean.getCoSoVatChatModel();
    			coSoVatChatModel.setTenCoSoVatChat(tenCoSoVatChatPhongBan);
    			coSoVatChatModel.setSoLuongDaTra(soLuongTra);
    			coSoVatChatModel.setSoLuongMuon(soLuongMuon);
    			try {
					if(JOptionPane.showConfirmDialog(null,this.tenNguoiMuon + " sẽ hoàn trả " + soLuongTra + " cái " + tenCoSoVatChatPhongBan , "Question?", JOptionPane.YES_NO_OPTION) == 0) {
                		if(muonTraService.hoanTraCoSoVatChatMuon(cccdNguoiMuon, coSoVatChatModel, thoiGianMuon))
                            {
                				JOptionPane.showMessageDialog(null, "Hoàn trả thành công " + soLuongTra + " cái " + tenCoSoVatChatPhongBan + " !!");
                                close();
                                parentController.refreshData();
                            } else {
                				JOptionPane.showMessageDialog(null, tenCoSoVatChatPhongBan + " đã được hoàn trả trước đây. Vui lòng chọn chỉnh sửa mượn trả nếu có sai sót xảy ra trong quá trình nhập!");
                            }
                	}
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
    		} else {
    			try {
    					if(JOptionPane.showConfirmDialog(null,tenCoSoVatChatPhongBan +" sẽ được bàn giao ?", "Question?", JOptionPane.YES_NO_OPTION) == 0) {
                    		if(muonTraService.hoanTraPhongBanMuon(this.cccdNguoiMuon, tenCoSoVatChatPhongBan, thoiGianMuon))
                                {
                    				JOptionPane.showMessageDialog(null, "Bàn giao " + tenCoSoVatChatPhongBan + " thành công!!");
                                    close();
                                    parentController.refreshData();
                                }
                    	}
    					return;
        
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
    		}
            
    	}
    }
    // check cac gia tri duoc nhap vao form
    private boolean validateValueInForm() {
        // check null
    	if(soLuongTraJtf.getText().trim().isEmpty()
    			) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập hết các trường bắt buộc", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
    	}
		int soLuongTra = Integer.parseInt(soLuongTraJtf.getText());
    	try {
    		if(soLuongTra < 0) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng số lượng", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
    		}
    	} catch (Exception e) {
			// TODO: handle exception
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng số lượng", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
		}
    	if(soLuongTra > Integer.parseInt(soLuongMuonDetailJlb.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng trả không thể lớn hơn số lượng mượn", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
    	}
        return true;
    }
	private XemChiTietMuonTraCotroller parentController;
    private JFrame parentFrame;
    private MuonTraBean muonTraBean;
    private AddNewController controller;
    private JPanel DangKyCoSoVatChatPanel;
    private JTextField soLuongTraJtf;
    private JLabel tenCoSoVatChatPhongBanDetailJlb;
    private String tenNguoiMuon;
    private String cccdNguoiMuon;
    private String thoiGianMuon;
    private int isCoSoVatChat;
    private JLabel soLuongMuonDetailJlb;
}
