/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.HoKhauPanelController;
import javax.swing.JFrame;
import views.HoKhauManagerFrame.ChuyenDiNoiKhac;
import views.HoKhauManagerFrame.FormDoiChuHo;
import views.HoKhauManagerFrame.FormTachHoKhau;
import views.HoKhauManagerFrame.FormThemHoKhau;
import views.HoKhauManagerFrame.FormThemThanhVien;
import views.HoKhauManagerFrame.FormXemChiTiet;
import views.HoKhauManagerFrame.TachHoKhau;
import views.HoKhauManagerFrame.ThemMoiHoKhau;
import views.HoKhauManagerFrame.XoaHoKhau;

import javax.swing.border.LineBorder;

import Bean.NhanKhauBean;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Ai làm thì diền tên vào
 */
public class HoKhauManagePanel extends javax.swing.JPanel {
    
    private JFrame parentFrame;
    private HoKhauPanelController controller;
    /**
     * Creates new form HoKhauManagePanel
     */
    public HoKhauManagePanel(JFrame parentFrame) {
    	setBorder(new LineBorder(new Color(0, 0, 0)));
        this.parentFrame = parentFrame;
        initComponents();
        controller = new HoKhauPanelController(jtfSearch, tableJpn, chuhotextField, diachitextField, locButton, popupMenu);
        controller.setParentJFrame(parentFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themMoiBtn = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        tachHoKhauBtn = new javax.swing.JButton();
        chuyenDiBtn = new javax.swing.JButton();
        tableJpn = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        themMoiBtn.setBackground(new java.awt.Color(255, 255, 255));
        themMoiBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        themMoiBtn.setText("Thêm mới");
        themMoiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMoiBtnActionPerformed(evt);
            }
        });

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });

        tachHoKhauBtn.setBackground(new java.awt.Color(255, 255, 255));
        tachHoKhauBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tachHoKhauBtn.setText("Tách HK");
        tachHoKhauBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	tachHoKhauBtnActionPerformed(evt);
            }
        });

        chuyenDiBtn.setBackground(new java.awt.Color(255, 255, 255));
        chuyenDiBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chuyenDiBtn.setText("Chuyển đi");
        chuyenDiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyenDiBtnActionPerformed(evt);
            }
        });
        
        popupMenu = new JPopupMenu();
        addPopup(tableJpn, popupMenu);
        
        XemMenuItem = new JMenuItem("Xem thông tin");
        popupMenu.add(XemMenuItem);
        XemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	xemBtnActionPerformed(evt);
            }
        });
        
        JMenuItem doichuhoMenuItem = new JMenuItem("Đổi chủ hộ");
        popupMenu.add(doichuhoMenuItem);
        doichuhoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	doiChuBtnActionPerformed(evt);
            }
        });
        
        themnhankhauMenuItem = new JMenuItem("Chỉnh sửa thành viên");
        popupMenu.add(themnhankhauMenuItem);
        themnhankhauMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	themThanhVienBtnActionPerformed(evt);
            }
        });
        
        tachMenuItem = new JMenuItem("Tách hộ khẩu");
        popupMenu.add(tachMenuItem);
        tachMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	tachHoKhauBtnActionPerformed(evt);
            }
        });
        
        JMenuItem xoa_ho_khauMenuItem = new JMenuItem("Xóa hộ khẩu");
        popupMenu.add(xoa_ho_khauMenuItem);
        xoa_ho_khauMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	chuyenDiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        
        maJLabel = new JLabel("Mã hộ khẩu");
        maJLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        
        chuhoJLabel = new JLabel("Tên chủ hộ");
        chuhoJLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        
        diachiJLabel = new JLabel("Địa chỉ");
        diachiJLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        
        chuhotextField = new JTextField();
        chuhotextField.setFont(new Font("Arial", Font.PLAIN, 14));
        
        diachitextField = new JTextField();
        diachitextField.setFont(new Font("Arial", Font.PLAIN, 14));
        
        locButton = new JButton("Lọc");
        locButton.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
                locButton.setBackground(new Color(12, 122, 10));
        	}
        	@Override
        	public void mousePressed(MouseEvent e) {
                locButton.setBackground(new Color(28, 155, 26));
        	}
        	
        	@Override
        	public void mouseReleased(MouseEvent e) {
                locButton.setBackground(new Color(12, 122, 10));
        	}
        	@Override
        	public void mouseExited(MouseEvent e) {
                locButton.setBackground(new Color(28, 155, 26));
        	}
        });
        locButton.setBorderPainted(false);
        locButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        locButton.setForeground(Color.WHITE);
        locButton.setFont(new Font("Tahoma", Font.BOLD, 14));
        locButton.setBackground(new Color(0, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(chuhoJLabel, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(chuhotextField, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(diachiJLabel, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(diachitextField, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(maJLabel, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jtfSearch, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
        				.addComponent(tableJpn, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						//.addComponent(tachHoKhauBtn, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        						//.addComponent(chuyenDiBtn, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        						.addComponent(themMoiBtn, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(locButton, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        					.addGap(42))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jtfSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(maJLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(chuhoJLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        				.addComponent(chuhotextField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(locButton, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(diachiJLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        				.addComponent(diachitextField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(themMoiBtn, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					//.addComponent(tachHoKhauBtn, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					//.addComponent(chuyenDiBtn, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(85, Short.MAX_VALUE))
        				.addComponent(tableJpn, GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void chuyenDiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyenDiBtnActionPerformed
    	JTable tempJTable = controller.getHoKhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	//ChuyenDiNoiKhac chuyenDiNoiKhac = new ChuyenDiNoiKhac(this.parentFrame);
        XoaHoKhau chuyenDiNoiKhac = new XoaHoKhau(this.controller, this.parentFrame, tempJTable);
        chuyenDiNoiKhac.setLocationRelativeTo(null);
        chuyenDiNoiKhac.setResizable(false);
        chuyenDiNoiKhac.setVisible(true);
    }//GEN-LAST:event_chuyenDiBtnActionPerformed
    
    private void xemBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	JTable tempJTable = controller.getHoKhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	FormXemChiTiet xem_chi_tiet = new FormXemChiTiet(this.parentFrame, tempJTable, controller);
    	xem_chi_tiet.setLocationRelativeTo(null);
    	xem_chi_tiet.setResizable(false);
    	xem_chi_tiet.setVisible(true);
    }

    private void themMoiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMoiBtnActionPerformed
    	//ThemMoiHoKhau themMoiHoKhau = new ThemMoiHoKhau(this.parentFrame);
    	FormThemHoKhau themMoiHoKhau = new FormThemHoKhau(this.controller, this.parentFrame);
        themMoiHoKhau.setLocationRelativeTo(null);
        themMoiHoKhau.setResizable(false);
        themMoiHoKhau.setVisible(true);
    }//GEN-LAST:event_themMoiBtnActionPerformed
    
    private void doiChuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMoiBtnActionPerformed
    	JTable tempJTable = controller.getHoKhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	FormDoiChuHo doi_chu_ho = new FormDoiChuHo(new NhanKhauBean(), this.parentFrame, tempJTable, controller);
    	doi_chu_ho.setLocationRelativeTo(null);
    	doi_chu_ho.setResizable(false);
    	doi_chu_ho.setVisible(true);
    }//GEN-LAST:event_themMoiBtnActionPerformed
    
    private void themThanhVienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMoiBtnActionPerformed
    	JTable tempJTable = controller.getHoKhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	FormThemThanhVien themMoiHoKhau = new FormThemThanhVien(new NhanKhauBean(), this.parentFrame, tempJTable);
        themMoiHoKhau.setLocationRelativeTo(null);
        themMoiHoKhau.setResizable(false);
        themMoiHoKhau.setVisible(true);
    }//GEN-LAST:event_themMoiBtnActionPerformed

    private void tachHoKhauBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tachHoKhauBtnActionPerformed
    	JTable tempJTable = controller.getHoKhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	//TachHoKhau tachHoKhau = new TachHoKhau(this.parentFrame);
        FormTachHoKhau tachHoKhau = new FormTachHoKhau(this.controller, this.parentFrame, tempJTable);
        tachHoKhau.setLocationRelativeTo(null);
        tachHoKhau.setResizable(false);
        tachHoKhau.setVisible(true);
    }//GEN-LAST:event_tachHoKhauBtnActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chuyenDiBtn;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JButton tachHoKhauBtn;
    private javax.swing.JButton themMoiBtn;
    private JLabel maJLabel;
    private JLabel chuhoJLabel;
    private JLabel diachiJLabel;
    private JTextField chuhotextField;
    private JTextField diachitextField;
    private JButton locButton;
    private JPopupMenu popupMenu;
    private JMenuItem tachMenuItem;
    private JMenuItem themnhankhauMenuItem;
    private JMenuItem XemMenuItem;
	private static void addPopup(Component component, final JPopupMenu popup) {
		component.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			public void mouseReleased(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			private void showMenu(MouseEvent e) {
				popup.show(e.getComponent(), e.getX(), e.getY());
			}
		});
	}
}
