package views;

import controllers.NhanKhauManagerPanelController;
import models.NhanKhauModel;
import views.NhanKhauManagerFrame.AddNewPeopleJFrame;
import views.NhanKhauManagerFrame.DangKyTamTru;
import views.NhanKhauManagerFrame.ThemMoiNhanKhau;
import views.NhanKhauManagerFrame.XemChiTietChinhSuaNhanKhau;
import views.NhanKhauManagerFrame.XoaNhanKhau;
import views.NhanKhauManagerFrame.DangKyTamTruJFrame;
import views.NhanKhauManagerFrame.DangKyTamVang;
import views.NhanKhauManagerFrame.DangKyTamVangJFrame;
import views.NhanKhauManagerFrame.KhaiTuJFrame;
import javax.swing.border.LineBorder;
import javax.swing.plaf.ColorUIResource;

import Bean.NhanKhauBean;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import javax.swing.JFrame;

/**
 *
 * @author Hai
 */
public class NhanKhauManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanKhauManagePanel
     */
    private NhanKhauManagerPanelController controller = null;
    private JFrame parentJFrame;
    
    public NhanKhauManagePanel(JFrame parentFrame) {
    	setBorder(new LineBorder(new Color(0, 0, 0)));
        this.parentJFrame = parentFrame;
        initComponents();
        controller = new NhanKhauManagerPanelController(tablePanel, tablepopupMenu, jtfSearch, diachiSearchtextField, locButton);
        controller.setParentJFrame(parentJFrame);
        controller.setDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //tamVangBtn = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        addNewBtn = new javax.swing.JButton();
        tamTruBtn = new javax.swing.JButton();
        khaiTuBtn = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

//        tamVangBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
//        tamVangBtn.setText("ĐK tạm vắng");
//        tamVangBtn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                tamVangBtnActionPerformed(evt);
//            }
//        });
        
        tablepopupMenu = new JPopupMenu();
        addPopup(tablePanel, tablepopupMenu);
        
        xemchitietvasuaMenuItem = new JMenuItem("Xem chi tiết và sửa");
        xemchitietvasuaMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ChinhSuaActionPerformed(e);
        	}
        });
        tablepopupMenu.add(xemchitietvasuaMenuItem);
        
        vangMenuItem = new JMenuItem("Đăng ký tạm vắng");
        vangMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		tamVangBtnActionPerformed(e);
        	}
        });
        tablepopupMenu.add(vangMenuItem);
        
        xoaMenuItem = new JMenuItem("Xóa");
        xoaMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		xoaActionPerformed(e);
        	}
        });
        tablepopupMenu.add(xoaMenuItem);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        addNewBtn.setBackground(new java.awt.Color(255, 255, 255));
        addNewBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addNewBtn.setText("Thêm mới");
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });

        tamTruBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tamTruBtn.setText("ĐK tạm trú");
        tamTruBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamTruBtnActionPerformed(evt);
            }
        });

        khaiTuBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        khaiTuBtn.setText("Khai Tử");
        khaiTuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khaiTuBtnActionPerformed(evt);
            }
        });

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
//        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jtfSearchActionPerformed(evt);
//            }
//        });
        
        hotenNewLabel = new JLabel("Họ và tên");
        hotenNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        locButton = new JButton("Lọc");
        locButton.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
                locButton.setBackground(new Color(12, 122, 10));
        	}
        	@Override
        	public void mousePressed(MouseEvent e) {
                locButton.setBackground(new Color(28, 155, 26));
        	}
        	
        	@Override
        	public void mouseReleased(MouseEvent e) {
                locButton.setBackground(new Color(12, 122, 10));
        	}
        	@Override
        	public void mouseExited(MouseEvent e) {
                locButton.setBackground(new Color(28, 155, 26));
        	}
        });
        locButton.setBorderPainted(false);
        locButton.setFont(new Font("Tahoma", Font.BOLD, 14));
        locButton.setBackground(new java.awt.Color(0, 160, 50));
        locButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        locButton.setForeground(Color.WHITE);
        
        diachiSearchtextField = new JTextField();
        diachiSearchtextField.setFont(new Font("Arial", Font.PLAIN, 14));
        
        JLabel lblaCh = new JLabel("Địa chỉ");
        lblaCh.setFont(new Font("Tahoma", Font.PLAIN, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblaCh, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(diachiSearchtextField, GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        				.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(hotenNewLabel)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jtfSearch, GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(addNewBtn, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        						.addComponent(tamTruBtn, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(locButton, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        					.addGap(37))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(hotenNewLabel)
        						.addComponent(jtfSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblaCh, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        						.addComponent(diachiSearchtextField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        					.addGap(8))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(locButton)
        					.addGap(18)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(addNewBtn, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addGap(36)
        					.addComponent(tamTruBtn, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addGap(18, 131, Short.MAX_VALUE))))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
//        AddNewPeopleJFrame addNewPeopleJFrame = new AddNewPeopleJFrame(this.controller, this.parentJFrame);
//        addNewPeopleJFrame.setLocationRelativeTo(null);
//        addNewPeopleJFrame.setResizable(false);
//        addNewPeopleJFrame.setVisible(true);
    	
        ThemMoiNhanKhau addNewPeopleJFrame = new ThemMoiNhanKhau(this.controller, this.parentJFrame);
        addNewPeopleJFrame.setLocationRelativeTo(null);
        addNewPeopleJFrame.setResizable(true);
        addNewPeopleJFrame.setVisible(true);
    	
        
    }//GEN-LAST:event_addNewBtnActionPerformed
    
    private void ChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
  	    
    	JTable tempJTable = controller.getNhankhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	List<NhanKhauBean> list = controller.getListNhanKhauBeans();
    	NhanKhauModel nhanKhauModel = list.get(row).getNhanKhauModel();
    	//System.err.println(nhanKhauModel.getTccString());
        XemChiTietChinhSuaNhanKhau xemChiTietChinhSuaNhanKhau = new XemChiTietChinhSuaNhanKhau(this.controller, this.parentJFrame, nhanKhauModel, tempJTable, row);
        xemChiTietChinhSuaNhanKhau.setLocationRelativeTo(null);
        xemChiTietChinhSuaNhanKhau.setResizable(false);
        xemChiTietChinhSuaNhanKhau.setVisible(true);
  	
      
    }

    private void tamVangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamVangBtnActionPerformed
        // hien jframe dang ky tam vang
    	JTable tempJTable = controller.getNhankhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	System.out.println("Hello");
    	
    	//DangKyTamVangJFrame dangKyTamVangJFrame = new DangKyTamVangJFrame(this.parentJFrame);
        DangKyTamVang dangKyTamVangJFrame = new DangKyTamVang(this.controller, this.parentJFrame);
        dangKyTamVangJFrame.setLocationRelativeTo(null);
        dangKyTamVangJFrame.setResizable(false);
        dangKyTamVangJFrame.setVisible(true);
    }//GEN-LAST:event_tamVangBtnActionPerformed

    private void tamTruBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamTruBtnActionPerformed
        DangKyTamTru dangKyTamTruJFrame = new DangKyTamTru(this.controller, this.parentJFrame);
        dangKyTamTruJFrame.setLocationRelativeTo(null);
        dangKyTamTruJFrame.setResizable(false);
        dangKyTamTruJFrame.setVisible(true);
    }//GEN-LAST:event_tamTruBtnActionPerformed

    private void khaiTuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khaiTuBtnActionPerformed
        KhaiTuJFrame khaiTuJFrame = new KhaiTuJFrame(this.parentJFrame);
        khaiTuJFrame.setLocationRelativeTo(null);
        khaiTuJFrame.setResizable(false);
        khaiTuJFrame.setVisible(true);
    }//GEN-LAST:event_khaiTuBtnActionPerformed
    
    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khaiTuBtnActionPerformed
    	JTable tempJTable = controller.getNhankhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	XoaNhanKhau xoaNhanKhau = new XoaNhanKhau(this.controller, this.parentJFrame, tempJTable, row);
    	xoaNhanKhau.setLocationRelativeTo(null);
    	xoaNhanKhau.setResizable(false);
    	xoaNhanKhau.setVisible(true);
    }//GEN-LAST:event_khaiTuBtnActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewBtn;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JButton khaiTuBtn;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton tamTruBtn;
    //private javax.swing.JButton tamVangBtn;
    private JLabel hotenNewLabel;
    private JButton locButton;
    private JPopupMenu tablepopupMenu;
    private JMenuItem vangMenuItem;
    private JMenuItem xemchitietvasuaMenuItem;
    private JMenuItem xoaMenuItem;
    private JTextField diachiSearchtextField;
    // End of variables declaration//GEN-END:variables
	private static void addPopup(Component component, final JPopupMenu popup) {
		component.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			public void mouseReleased(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			private void showMenu(MouseEvent e) {
				popup.show(e.getComponent(), e.getX(), e.getY());
			}
		});
	}
}
