package views;

import controllers.CoSoVatChatPanelController;
import controllers.MuonTraPanelController;
import services.StringService;

import javax.swing.JFrame;

import views.CoSoVatChatFrame.ThemCoSoVatChatFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import java.awt.Rectangle;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.border.LineBorder;
import java.awt.Insets;
import javax.swing.border.CompoundBorder;
import javax.swing.UIManager;
import javax.swing.SwingConstants;

/**
 *
 * @author Hai
 */
public class CoSoVatChatPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanKhauManagePanel
     */
    private CoSoVatChatPanelController controller = null;
    private JFrame parentJFrame;
    
    public CoSoVatChatPanel(JFrame parentFrame) {
        this.parentJFrame = parentFrame;
        initComponents();
        controller = new CoSoVatChatPanelController(tablePanel, searchJtf);
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 566, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 211, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        controller.setParentJFrame(parentJFrame);
        controller.setDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        tablePanel = new javax.swing.JPanel();
        
        addNewBtn = new javax.swing.JButton();
        addNewBtn.setBorder(null);
        addNewBtn.setIcon(new ImageIcon(CoSoVatChatPanel.class.getResource("/Icons/add.png")));

        setBackground(new java.awt.Color(255, 255, 255));

        addNewBtn.setBackground(new java.awt.Color(255, 255, 255));
        addNewBtn.setFont(new Font("Arial", Font.BOLD, 10));
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });
        
        JPanel searchPanel = new JPanel();
        searchPanel.setBorder(UIManager.getBorder("TextField.border"));
        searchPanel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        searchPanel.setBackground(Color.WHITE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(tablePanel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(searchPanel, GroupLayout.PREFERRED_SIZE, 312, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
        					.addComponent(addNewBtn, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(51)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(addNewBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(27))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(searchPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(23)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(56, Short.MAX_VALUE))
        );
        
        searchJtf = new JTextField();
        searchJtf.setBorder(null);
        searchJtf.setColumns(10);
        
        JButton searchJbutton = new JButton("");
        searchJbutton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		jtfSearchActionPerformed(evt);
        	}
        });
        searchJbutton.setBorder(null);
        searchJbutton.setIcon(new ImageIcon(CoSoVatChatPanel.class.getResource("/Icons/search.png")));
        searchJbutton.setBackground(Color.WHITE);
        GroupLayout gl_searchPanel = new GroupLayout(searchPanel);
        gl_searchPanel.setHorizontalGroup(
        	gl_searchPanel.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_searchPanel.createSequentialGroup()
        			.addComponent(searchJtf, GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        			.addGap(48)
        			.addComponent(searchJbutton, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
        );
        gl_searchPanel.setVerticalGroup(
        	gl_searchPanel.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, gl_searchPanel.createParallelGroup(Alignment.BASELINE)
        			.addComponent(searchJtf, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        			.addComponent(searchJbutton, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        );
        searchPanel.setLayout(gl_searchPanel);
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    
    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
    	ThemCoSoVatChatFrame ThemCoSoVatChatFrame = new ThemCoSoVatChatFrame(this.controller, this.parentJFrame);
    	ThemCoSoVatChatFrame.setLocationRelativeTo(null);
    	ThemCoSoVatChatFrame.setResizable(false);
    	ThemCoSoVatChatFrame.setVisible(true);
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
    	String tenCoSoVatChat = StringService.covertToString(searchJtf.getText());
    	controller.initAction(tenCoSoVatChat);
    }//GEN-LAST:event_jtfSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewBtn;
    private javax.swing.JPanel tablePanel;
    private JTextField searchJtf;
}
