/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Bean.DanhMucBean;
import controllers.MainController;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author Hai
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("QUẢN LÝ NHÂN KHẨU");
        List<DanhMucBean> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMucBean("TrangChu", Home, jblTrangChu));
        listDanhMuc.add(new DanhMucBean("CoSoVatChat", CoSoVatChat, jblCoSoVatChat));
        listDanhMuc.add(new DanhMucBean("PhongBan", PhongBan, jblPhongBan));
        listDanhMuc.add(new DanhMucBean("MuonTra", MuonTra, jblMuontra));
        listDanhMuc.add(new DanhMucBean("LichSu", LichSu, jblLichSu));
        listDanhMuc.forEach((item) -> {
        	System.out.println(item.getJlb().getText());
        });
        MainController controller = new MainController(jpnBean, this);
        controller.setView(Home, jblTrangChu, "TrangChu");
        controller.setEvent(listDanhMuc);
        
        // confirm de thuc hien dong
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Confirm", JOptionPane.YES_NO_OPTION) == 0) {
                    dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/house.png")));
        jpnContainer = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jblTrangChu = new javax.swing.JLabel();
        jpnBean = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnContainer.setBackground(new java.awt.Color(255, 255, 255));

        jpnMenu.setBackground(new java.awt.Color(153, 153, 153));

        Home.setBackground(new java.awt.Color(0, 160, 50));

        jblTrangChu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jblTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/app.png"))); // NOI18N
        jblTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTrangChu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jblTrangChu)
                .addGap(21, 21, 21))
        );
        
        MuonTra = new JPanel();
        MuonTra.setBackground(new Color(102, 102, 102));
        
        jblMuontra = new JLabel();
        jblMuontra.setText("Mượn Trả");
        jblMuontra.setForeground(Color.WHITE);
        jblMuontra.setFont(new Font("Arial", Font.BOLD, 16));
        GroupLayout gl_MuonTra = new GroupLayout(MuonTra);
        gl_MuonTra.setHorizontalGroup(
        	gl_MuonTra.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_MuonTra.createSequentialGroup()
        			.addGap(38)
        			.addComponent(jblMuontra, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        gl_MuonTra.setVerticalGroup(
        	gl_MuonTra.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, gl_MuonTra.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jblMuontra, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        			.addContainerGap())
        );
        MuonTra.setLayout(gl_MuonTra);
        
        CoSoVatChat = new JPanel();
        CoSoVatChat.setBackground(new Color(102, 102, 102));
        
        jblCoSoVatChat = new JLabel();
        jblCoSoVatChat.setText("Cơ sở vật chất");
        jblCoSoVatChat.setForeground(Color.WHITE);
        jblCoSoVatChat.setFont(new Font("Arial", Font.BOLD, 16));
        GroupLayout gl_CoSoVatChat = new GroupLayout(CoSoVatChat);
        gl_CoSoVatChat.setHorizontalGroup(
        	gl_CoSoVatChat.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_CoSoVatChat.createSequentialGroup()
        			.addGap(18)
        			.addComponent(jblCoSoVatChat)
        			.addContainerGap(29, Short.MAX_VALUE))
        );
        gl_CoSoVatChat.setVerticalGroup(
        	gl_CoSoVatChat.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, gl_CoSoVatChat.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jblCoSoVatChat, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        			.addContainerGap())
        );
        CoSoVatChat.setLayout(gl_CoSoVatChat);
        
        LichSu = new JPanel();
        LichSu.setBackground(new Color(102, 102, 102));
        
        jblLichSu = new JLabel();
        jblLichSu.setText("Lịch sử");
        jblLichSu.setForeground(Color.WHITE);
        jblLichSu.setFont(new Font("Arial", Font.BOLD, 16));
        GroupLayout gl_LichSu = new GroupLayout(LichSu);
        gl_LichSu.setHorizontalGroup(
        	gl_LichSu.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, gl_LichSu.createSequentialGroup()
        			.addGap(36)
        			.addComponent(jblLichSu, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(37, Short.MAX_VALUE))
        );
        gl_LichSu.setVerticalGroup(
        	gl_LichSu.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_LichSu.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jblLichSu, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        			.addContainerGap())
        );
        LichSu.setLayout(gl_LichSu);
        
        PhongBan = new JPanel();
        PhongBan.setBackground(new Color(102, 102, 102));
        
        jblPhongBan = new JLabel();
        jblPhongBan.setText("Phòng ban");
        jblPhongBan.setForeground(Color.WHITE);
        jblPhongBan.setFont(new Font("Arial", Font.BOLD, 16));
        GroupLayout gl_PhongBan = new GroupLayout(PhongBan);
        gl_PhongBan.setHorizontalGroup(
        	gl_PhongBan.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, gl_PhongBan.createSequentialGroup()
        			.addGap(31)
        			.addComponent(jblPhongBan, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(35, Short.MAX_VALUE))
        );
        gl_PhongBan.setVerticalGroup(
        	gl_PhongBan.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, gl_PhongBan.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jblPhongBan, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        			.addContainerGap())
        );
        PhongBan.setLayout(gl_PhongBan);

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenuLayout.setHorizontalGroup(
        	jpnMenuLayout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(Home, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        		.addGroup(jpnMenuLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(CoSoVatChat, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        		.addGroup(jpnMenuLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(LichSu, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        		.addGroup(jpnMenuLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(MuonTra, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        		.addGroup(jpnMenuLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(PhongBan, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
        	jpnMenuLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpnMenuLayout.createSequentialGroup()
        			.addComponent(Home, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addComponent(CoSoVatChat, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(PhongBan, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(MuonTra, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(LichSu, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(148, Short.MAX_VALUE))
        );
        jpnMenu.setLayout(jpnMenuLayout);

        javax.swing.GroupLayout jpnBeanLayout = new javax.swing.GroupLayout(jpnBean);
        jpnBean.setLayout(jpnBeanLayout);
        jpnBeanLayout.setHorizontalGroup(
            jpnBeanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jpnBeanLayout.setVerticalGroup(
            jpnBeanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnContainerLayout = new javax.swing.GroupLayout(jpnContainer);
        jpnContainer.setLayout(jpnContainerLayout);
        jpnContainerLayout.setHorizontalGroup(
            jpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnContainerLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnBean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnContainerLayout.setVerticalGroup(
            jpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnBean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JPanel Home;
    private javax.swing.JLabel jblTrangChu;
    private javax.swing.JPanel jpnBean;
    private javax.swing.JPanel jpnContainer;
    private javax.swing.JPanel jpnMenu;
    private JPanel MuonTra;
    private JLabel jblMuontra;
    private JPanel CoSoVatChat;
    private JLabel jblCoSoVatChat;
    private JLabel jblPhongBan;
    private JPanel PhongBan;
    private JLabel jblLichSu;
    private JPanel LichSu;
}
