package views;

import controllers.MuonTraManagerPanelController;
import services.StringService;

import javax.swing.JFrame;

import views.MuonTraFrame.ThemCoSoVatChatFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import java.awt.Rectangle;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Hai
 */
public class MuonTraPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanKhauManagePanel
     */
    private MuonTraManagerPanelController controller = null;
    private JFrame parentJFrame;
    
    public MuonTraPanel(JFrame parentFrame) {
        this.parentJFrame = parentFrame;
        initComponents();
        controller = new MuonTraManagerPanelController(tablePanel, nguoiMuonJtfSearch, lienheJtfSearch, toJtfSearch, fromJtfSearch);
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 566, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 211, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        controller.setParentJFrame(parentJFrame);
        controller.setDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        tablePanel = new javax.swing.JPanel();
        
        addNewBtn = new javax.swing.JButton();
        addNewBtn.setIcon(new ImageIcon(MuonTraPanel.class.getResource("/Icons/add.png")));
        nguoiMuonJtfSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        addNewBtn.setBackground(new java.awt.Color(255, 255, 255));
        addNewBtn.setFont(new java.awt.Font("Arial", 1, 14));
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });

        nguoiMuonJtfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        
        JLabel lblNewLabel = new JLabel("Người mượn:");
        lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        JLabel lblNewLabel_1 = new JLabel("Liên hệ:");
        lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        lienheJtfSearch = new JTextField();
        lienheJtfSearch.setFont(new Font("Tahoma", Font.PLAIN, 14));
        lienheJtfSearch.setColumns(10);
        
        JPanel SearchTImepanel = new JPanel();
        SearchTImepanel.setBorder(new LineBorder(new Color(0, 0, 0)));
        SearchTImepanel.setBackground(Color.WHITE);
        
        JButton filterJButton = new JButton("Lọc");
        filterJButton.setAlignmentY(Component.TOP_ALIGNMENT);
        filterJButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		jtfSearchActionPerformed(evt);
        	}
        });
        filterJButton.setForeground(Color.WHITE);
        filterJButton.setBackground(new Color(28, 155, 26));
        filterJButton.setFont(new Font("Tahoma", Font.PLAIN, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(10)
        							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        							.addGap(26)
        							.addComponent(nguoiMuonJtfSearch, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        							.addGap(47)
        							.addComponent(lblNewLabel_1)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(lienheJtfSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(SearchTImepanel, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(filterJButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        					.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        					.addComponent(addNewBtn, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lienheJtfSearch, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel_1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(2)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(nguoiMuonJtfSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(SearchTImepanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(filterJButton)
        						.addComponent(addNewBtn, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))))
        			.addGap(8)
        			.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        timeJLabel = new JLabel("Thời gian mượn:");
        timeJLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        fromJLabel = new JLabel("Từ");
        fromJLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        fromJtfSearch = new JTextField();
        fromJtfSearch.setFont(new Font("Tahoma", Font.PLAIN, 14));
        fromJtfSearch.setColumns(10);
        
        toJLabel = new JLabel("Đến");
        toJLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        toJtfSearch = new JTextField();
        toJtfSearch.setFont(new Font("Tahoma", Font.PLAIN, 14));
        toJtfSearch.setColumns(10);
        GroupLayout gl_SearchTImepanel = new GroupLayout(SearchTImepanel);
        gl_SearchTImepanel.setHorizontalGroup(
        	gl_SearchTImepanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_SearchTImepanel.createSequentialGroup()
        			.addGap(6)
        			.addComponent(timeJLabel, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(fromJLabel)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(fromJtfSearch, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        			.addGap(27)
        			.addComponent(toJLabel)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(toJtfSearch, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(30, Short.MAX_VALUE))
        );
        gl_SearchTImepanel.setVerticalGroup(
        	gl_SearchTImepanel.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_SearchTImepanel.createSequentialGroup()
        			.addGroup(gl_SearchTImepanel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_SearchTImepanel.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(gl_SearchTImepanel.createParallelGroup(Alignment.BASELINE)
        						.addComponent(fromJLabel)
        						.addComponent(timeJLabel, GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
        				.addGroup(gl_SearchTImepanel.createSequentialGroup()
        					.addGap(14)
        					.addGroup(gl_SearchTImepanel.createParallelGroup(Alignment.BASELINE)
        						.addComponent(fromJtfSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(toJLabel)
        						.addComponent(toJtfSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        SearchTImepanel.setLayout(gl_SearchTImepanel);
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
    	ThemCoSoVatChatFrame themCoSoVatChatFrame = new ThemCoSoVatChatFrame(this.controller, this.parentJFrame);
    	themCoSoVatChatFrame.setLocationRelativeTo(null);
    	themCoSoVatChatFrame.setResizable(false);
    	themCoSoVatChatFrame.setVisible(true);
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
    	String tenNguoiMuon = StringService.covertToString(nguoiMuonJtfSearch.getText());
    	String lienHe = StringService.covertToString(lienheJtfSearch.getText());
    	String tuNgay = StringService.covertToString(toJtfSearch.getText());
    	String denNgay = StringService.covertToString(fromJtfSearch.getText());
    	controller.initAction(tenNguoiMuon, lienHe, tuNgay, denNgay);
    }//GEN-LAST:event_jtfSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewBtn;
    private javax.swing.JTextField nguoiMuonJtfSearch;
    private javax.swing.JPanel tablePanel;
    private JTextField lienheJtfSearch;
    private JLabel timeJLabel;
    private JLabel fromJLabel;
    private JTextField fromJtfSearch;
    private JLabel toJLabel;
    private JTextField toJtfSearch;
}
