package views.HoKhauManagerFrame;

import Bean.NhanKhauBean;
import controllers.HoKhauManagerController.ChonChuHoMoiController;
import controllers.HoKhauManagerController.ChonThanhVienController;
import controllers.HoKhauManagerController.ChoosePeopleController;
import controllers.HoKhauManagerController.QuanLyThanhVienController;
import models.NhanKhauModel;
import services.HoKhauService;
import views.NhanKhauManagerFrame.ThemMoiNhanKhau;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPanel;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Hai
 */
public class FormThemThanhVien extends javax.swing.JFrame {

    private NhanKhauBean nhanKhauBean;
    private NhanKhauBean nhanKhauBeanTemp;
    private JFrame parentJFrame;
    private ChonThanhVienController controller;
    private QuanLyThanhVienController quan_lycontroller;
    private JTable parenTable;
    private int id_ho_khau;
    //private final ChoosePeopleController controller;
    
    /**
     * Creates new form ChoosePeople
     * @param nhanKhauBean nhan khau duoc truyen vao tu frame cha
     * @param parentJframe frame cha de disable
     */
    public FormThemThanhVien(NhanKhauBean nhanKhauBean, JFrame parentJframe, JTable parenTable) {
    	setTitle("Điều chỉnh thành viên trong hộ");
        initComponents();
        this.nhanKhauBean = nhanKhauBean;
        this.parentJFrame = parentJframe;
        this.parenTable = parenTable;
        this.nhanKhauBeanTemp = new NhanKhauBean();
        this.id_ho_khau = (int)this.parenTable.getModel().getValueAt(parenTable.getSelectedRow(),3);
//        this.hotenField = hotenField;
//        this.id_chuho = id_chuho;
        parentJframe.setEnabled(false);
        controller = new ChonThanhVienController(this.tableJpn, this.ho_tentextField, this.locButton);
        quan_lycontroller = new QuanLyThanhVienController(this.thanh_vien_tablepanel, this.ho_tentextField, this.locButton, this.id_ho_khau);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJframe.setEnabled(true);
                Close();
            }
            
        });
    }
    
    public void Close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    public NhanKhauBean getNhanKhauBean() {
        return nhanKhauBean;
    }

    public void setNhanKhauBean(NhanKhauBean nhanKhauBean) {
        this.nhanKhauBean = nhanKhauBean;
    }

    public JFrame getParentJFrame() {
        return parentJFrame;
    }

    public void setParentJFrame(JFrame parentJFrame) {
        this.parentJFrame = parentJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tableJpn = new javax.swing.JPanel();
        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        
        hoanthanhButton = new JButton("Thêm");
        hoanthanhButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ThemThanhVienBtnActionPerformed(e);
        	}
        });
        hoanthanhButton.setForeground(Color.WHITE);
        hoanthanhButton.setFont(new Font("Tahoma", Font.BOLD, 14));
        hoanthanhButton.setBorderPainted(false);
        hoanthanhButton.setBackground(new Color(212, 84, 21));
        
        ho_tenLable = new JLabel("Họ tên:");
        ho_tenLable.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        ho_tentextField = new JTextField();
        ho_tentextField.setFont(new Font("Arial", Font.PLAIN, 14));
        
        locButton = new JButton("Lọc");
        locButton.setForeground(Color.WHITE);
        locButton.setFont(new Font("Tahoma", Font.BOLD, 14));
        locButton.setBorderPainted(false);
        locButton.setBackground(new Color(0, 160, 50));
        
        JLabel ho_tenLable_1 = new JLabel("Thành viên trong hộ:");
        ho_tenLable_1.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 12));
        
        thanh_vien_tablepanel = new JPanel();
        javax.swing.GroupLayout gl_thanh_vien_tablepanel = new javax.swing.GroupLayout(thanh_vien_tablepanel);
        thanh_vien_tablepanel.setLayout(gl_thanh_vien_tablepanel);
        gl_thanh_vien_tablepanel.setHorizontalGroup(
        		gl_thanh_vien_tablepanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gl_thanh_vien_tablepanel.setVerticalGroup(
        		gl_thanh_vien_tablepanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        
        btnBt = new JButton("Bớt");
        btnBt.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		BotThanhVienBtnActionPerformed(e);
        	}
        });
        btnBt.setForeground(Color.WHITE);
        btnBt.setFont(new Font("Tahoma", Font.BOLD, 14));
        btnBt.setBorderPainted(false);
        btnBt.setBackground(new Color(212, 84, 21));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(thanh_vien_tablepanel, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(ho_tenLable, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(ho_tentextField, 453, 453, 453))
        						.addComponent(tableJpn, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(hoanthanhButton, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(30)
        							.addComponent(locButton, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(btnBt, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))))
        				.addComponent(ho_tenLable_1, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(12)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(ho_tenLable, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(ho_tentextField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        					.addComponent(locButton, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)))
        			.addGap(31)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(hoanthanhButton, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        				.addComponent(tableJpn, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addComponent(ho_tenLable_1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(thanh_vien_tablepanel, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBt, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thanh_vien_tablepanel.setLayout(null);
        tableJpn.setLayout(null);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tableJpn;
    private JPanel thanh_vien_tablepanel;
    private JButton hoanthanhButton;
    private JLabel ho_tenLable;
    private JTextField ho_tentextField;
    private JButton locButton;
    private JButton btnBt;
    
    private void ThemThanhVienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
    	JTable tempJTable = controller.getNhankhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	int id_nhan_khau = (int)tempJTable.getModel().getValueAt(tempJTable.getSelectedRow(),0);
    	id_ho_khau = (int)this.parenTable.getModel().getValueAt(parenTable.getSelectedRow(),3);
        try {
			new HoKhauService().addThanhVien(id_nhan_khau, id_ho_khau);
			JOptionPane.showMessageDialog(null, "Thêm thành công!!");
	        controller.refreshData();
	        quan_lycontroller.refreshData();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
//        try {
//            if (this.controller.addNewPeople(this.nhanKhauBean)) {
//                JOptionPane.showMessageDialog(null, "Thêm thành công!!");
//                close();
//                parentController.refreshData();
//            }
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//            JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_CreateBtnActionPerformed
    private void BotThanhVienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
    	JTable tempJTable = quan_lycontroller.getNhankhauTable();
    	int row = tempJTable.getSelectedRow();
    	if (row == -1) {
    		JOptionPane.showMessageDialog(null, "Hãy lựa chọn một hàng trước",
    			      "Lỗi không chọn hàng!", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	int id_nhan_khau = (int)tempJTable.getModel().getValueAt(tempJTable.getSelectedRow(),0);
    	id_ho_khau = (int)this.parenTable.getModel().getValueAt(parenTable.getSelectedRow(),3);
        try {
			new HoKhauService().subThanhVien(id_nhan_khau, id_ho_khau);
			JOptionPane.showMessageDialog(null, "Bớt thành công!!");
	        controller.refreshData();
	        quan_lycontroller.refreshData();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
    }//GEN-LAST:event_CreateBtnActionPerformed
}



