package views.HoKhauManagerFrame;

import Bean.HoKhauBean;
import Bean.NhanKhauBean;
import controllers.HoKhauPanelController;
import controllers.HoKhauManagerController.ChonThanhVienController;
import controllers.HoKhauManagerController.ChoosePeopleController;
import controllers.HoKhauManagerController.QuanLyQuanHeController;
import controllers.HoKhauManagerController.QuanLyThanhVienController;
import models.NhanKhauModel;
import services.HoKhauService;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Hai
 */
public class FormXemChiTiet extends javax.swing.JFrame {

    private NhanKhauBean nhanKhauBean;
    private NhanKhauModel chuHoModel;
    private JFrame parentJFrame;
    private QuanLyQuanHeController quan_lycontroller;
    private JTable parenTable;
    private int id_ho_khau;
    private HoKhauPanelController parent_controller;
    //private final ChoosePeopleController controller;
    
    /**
     * Creates new form ChoosePeople
     * @param nhanKhauBean nhan khau duoc truyen vao tu frame cha
     * @param parentJframe frame cha de disable
     */
    public FormXemChiTiet(JFrame parentJframe, JTable parenTable, HoKhauPanelController parent_controller) {
    	setTitle("Xem chi tiết");
        this.parentJFrame = parentJframe;
        this.parenTable = parenTable;
        this.parent_controller = parent_controller;
        this.id_ho_khau = (int)this.parenTable.getModel().getValueAt(parenTable.getSelectedRow(),3);
        try {
			this.chuHoModel = new HoKhauService().getThongTinChuHo(this.id_ho_khau);
		} catch (ClassNotFoundException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
//        this.hotenField = hotenField;
//        this.id_chuho = id_chuho;

        initComponents();
        parentJframe.setEnabled(false);
        quan_lycontroller = new QuanLyQuanHeController(this.tableJpn, this.ho_tentextField, this.locButton, this.id_ho_khau);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJframe.setEnabled(true);
                Close();
            }
            
        });
    }
    
    public void Close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    public NhanKhauBean getNhanKhauBean() {
        return nhanKhauBean;
    }

    public void setNhanKhauBean(NhanKhauBean nhanKhauBean) {
        this.nhanKhauBean = nhanKhauBean;
    }

    public JFrame getParentJFrame() {
        return parentJFrame;
    }

    public void setParentJFrame(JFrame parentJFrame) {
        this.parentJFrame = parentJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tableJpn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        
        ho_tenLable = new JLabel("Họ tên chủ hộ:");
        ho_tenLable.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        ho_tentextField = new JTextField();
        ho_tentextField.setEnabled(false);
        ho_tentextField.setEditable(false);
        ho_tentextField.setFont(new Font("Arial", Font.PLAIN, 14));
        ho_tentextField.setText(this.chuHoModel.getHoTen());
        
        locButton = new JButton("Lọc");
        locButton.setForeground(Color.WHITE);
        locButton.setFont(new Font("Tahoma", Font.BOLD, 14));
        locButton.setBorderPainted(false);
        locButton.setBackground(new Color(0, 160, 50));
        
        JLabel ngay_sinhLable = new JLabel("Ngày sinh chủ hộ:");
        ngay_sinhLable.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        gioi_tinhLabel = new JLabel("Giới tính chủ hộ:");
        gioi_tinhLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        gioi_tinh_textField = new JTextField();
        gioi_tinh_textField.setText(this.chuHoModel.getGioiTinh());;
        gioi_tinh_textField.setFont(new Font("Arial", Font.PLAIN, 14));
        gioi_tinh_textField.setEditable(false);
        
        String pattern = "MM/dd/yyyy";
        DateFormat df = new SimpleDateFormat(pattern);
        ngay_sinh_textField = new JTextField();
        ngay_sinh_textField.setText(df.format(this.chuHoModel.getNamSinh()));
        ngay_sinh_textField.setFont(new Font("Arial", Font.PLAIN, 14));
        ngay_sinh_textField.setEditable(false);
        
        lblNhypChut = new JLabel("Nháy đúp chuột trái vào hàng tương ứng để sửa quan hệ với chủ hộ");
        lblNhypChut.setForeground(new Color(50, 205, 50));
        lblNhypChut.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 16));
        lblNhypChut.setBackground(Color.WHITE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        						.addComponent(tableJpn, GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        						.addContainerGap())
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(ngay_sinhLable, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(ngay_sinh_textField, GroupLayout.PREFERRED_SIZE, 291, GroupLayout.PREFERRED_SIZE)
        						.addContainerGap(240, Short.MAX_VALUE))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(ho_tenLable, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(ho_tentextField, GroupLayout.PREFERRED_SIZE, 291, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
        						.addComponent(gioi_tinhLabel, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(gioi_tinh_textField, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        						.addGap(15)))
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addComponent(lblNhypChut, GroupLayout.PREFERRED_SIZE, 576, GroupLayout.PREFERRED_SIZE)
        					.addGap(45))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(12)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(ho_tenLable, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ho_tentextField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(gioi_tinhLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        				.addComponent(gioi_tinh_textField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(ngay_sinhLable, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ngay_sinh_textField, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(tableJpn, GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNhypChut, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tableJpn;
    private JLabel ho_tenLable;
    private JTextField ho_tentextField;
    private JButton locButton;
    private JLabel gioi_tinhLabel;
    private JTextField gioi_tinh_textField;
    private JTextField ngay_sinh_textField;
    private JLabel lblNhypChut;
}
