package views.CoSoVatChatFrame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import controllers.CoSoVatChatPanelController;
import controllers.CoSoVatChatController.XemChiTietCoSoVatChatCotroller;
import services.CoSoVatChatService;
import views.MuonTraFrame.DangKySuDungFrame;
import views.MuonTraFrame.MuonCoSoVatChatPhongBanFrame;
import models.CoSoVatChatModel;
import models.NhaTaiTroModel;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;

import Bean.CoSoVatChatBean;
import ControllersAddNewController.AddNewController;

import javax.swing.JScrollPane;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.JPanel;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.ComponentOrientation;

public class ThemSoLuongCoSoVatChatFrame extends javax.swing.JFrame {
	 /**
     * Creates new form AddNewPeopleJFrame
     */



//    public AddNewPeopleJFrame() {
//        initComponents();
//        setTitle("Thêm mới nhân khẩu");
//        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        controller = new AddNewController();
//    }

    /**
     * @wbp.parser.constructor
     */
    public ThemSoLuongCoSoVatChatFrame(CoSoVatChatPanelController parentController, JFrame parentJFrame, String tenCoSoVatChatDetail, String tongSoLuong, String soLuongMuon, String soLuongTrongKho) {
    	setBackground(new Color(255, 228, 228));
    	this.parentController = parentController;
    	this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        initComponents();
    	this.tenCoSoVatChatDetail.setText(tenCoSoVatChatDetail);
    	this.tongSoLuongDetail.setText(tongSoLuong);
    	this.soLuongMuonDetail.setText(soLuongMuon);
    	this.soLuongTrongKhoDetail.setText(soLuongTrongKho);
    	setIconImage(Toolkit.getDefaultToolkit().getImage(ThemCoSoVatChatFrame.class.getResource("/Icons/house.png")));
    	setTitle("Xóa cơ sở vật chất");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
        controller = new AddNewController();
    }
    
    public ThemSoLuongCoSoVatChatFrame(JFrame parentJFrame) {
        this.parentController = new CoSoVatChatPanelController(){
            @Override
            public void refreshData() {
                // do nothing
            }

            @Override
            public void initAction() {
                // do nothing
            }
            
            
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.coSoVatChatBean = new CoSoVatChatBean();
        initComponents();
        setTitle("Xóa cơ sở vật chất");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new AddNewController();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	DangKyCoSoVatChatPanel = new JPanel();
    	DangKyCoSoVatChatPanel.setBackground(new Color(255, 228, 228));
    	getContentPane().add(DangKyCoSoVatChatPanel, BorderLayout.CENTER);
    	
    	JLabel tenCoSoVatChatJlb = new JLabel("Tên cơ sở vật chất:");
    	tenCoSoVatChatJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JLabel tongSoLuongJlb = new JLabel("Tổng số lượng:");
    	tongSoLuongJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JLabel soLuongMuonJlb = new JLabel("Số lượng mượn:");
    	soLuongMuonJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JButton okButton = new JButton("OK");
    	okButton.addMouseListener(new MouseAdapter() {
    		
    		@Override
        	public void mouseEntered(MouseEvent e) {
                okButton.setBackground(new Color(195, 66, 2));
        	}
    		@Override
        	public void mousePressed(MouseEvent e) {
            	okButton.setBackground(new Color(212, 84, 21));
        	}
    		@Override
        	public void mouseReleased(MouseEvent e) {
                okButton.setBackground(new Color(195, 66, 2));
        	}
    		@Override
        	public void mouseExited(MouseEvent e) {
            	okButton.setBackground(new Color(212, 84, 21));
        	}
    	});
    	okButton.setBorder(null);
    	okButton.setForeground(Color.WHITE);
    	okButton.setFont(new Font("Tahoma", Font.BOLD, 16));
    	okButton.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent evt) {
    			xoaCoSoVatChatActionPerformed(evt);
    		}
    	});
    	okButton.setBackground(new Color(212, 84, 21));
    	
    	tenCoSoVatChatDetail = new JLabel("null");
    	tenCoSoVatChatDetail.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	tongSoLuongDetail = new JLabel("null");
    	tongSoLuongDetail.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	soLuongMuonDetail = new JLabel("null");
    	soLuongMuonDetail.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JLabel soLuongTrongKhoJlb = new JLabel("Số lượng trong kho:");
    	soLuongTrongKhoJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	soLuongTrongKhoDetail = new JLabel("null");
    	soLuongTrongKhoDetail.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	JLabel soLuongXoaJlb = new JLabel("Số lượng thêm:");
    	soLuongXoaJlb.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	
    	soLuongXoaJtf = new JTextField();
    	soLuongXoaJtf.setBorder(null);
    	soLuongXoaJtf.setFont(new Font("Tahoma", Font.PLAIN, 14));
    	soLuongXoaJtf.setColumns(10);
    	GroupLayout gl_DangKyCoSoVatChatPanel = new GroupLayout(DangKyCoSoVatChatPanel);
    	gl_DangKyCoSoVatChatPanel.setHorizontalGroup(
    		gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addContainerGap()
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    							.addComponent(tongSoLuongJlb, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
    							.addComponent(soLuongMuonJlb, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
    							.addComponent(tenCoSoVatChatJlb)
    							.addComponent(soLuongTrongKhoJlb, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE))
    						.addGap(18)
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    							.addComponent(tenCoSoVatChatDetail, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
    							.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    								.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    									.addGroup(Alignment.TRAILING, gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    										.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING)
    											.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    												.addComponent(soLuongTrongKhoDetail, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
    												.addGap(180))
    											.addGroup(Alignment.LEADING, gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    												.addComponent(soLuongMuonDetail, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
    												.addGap(180)))
    										.addPreferredGap(ComponentPlacement.RELATED))
    									.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    										.addComponent(tongSoLuongDetail, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
    										.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    								.addPreferredGap(ComponentPlacement.RELATED)
    								.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
    								.addGap(10))))
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addComponent(soLuongXoaJlb, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
    						.addGap(18)
    						.addComponent(soLuongXoaJtf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
    				.addContainerGap())
    	);
    	gl_DangKyCoSoVatChatPanel.setVerticalGroup(
    		gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    			.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    				.addGap(24)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.TRAILING)
    					.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
    					.addGroup(gl_DangKyCoSoVatChatPanel.createSequentialGroup()
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    							.addComponent(tenCoSoVatChatJlb)
    							.addComponent(tenCoSoVatChatDetail))
    						.addPreferredGap(ComponentPlacement.UNRELATED)
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    							.addComponent(tongSoLuongJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    							.addComponent(tongSoLuongDetail, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
    						.addPreferredGap(ComponentPlacement.RELATED)
    						.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.LEADING)
    							.addComponent(soLuongMuonJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    							.addComponent(soLuongMuonDetail, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))))
    				.addPreferredGap(ComponentPlacement.RELATED)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    					.addComponent(soLuongTrongKhoJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    					.addComponent(soLuongTrongKhoDetail, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
    				.addGap(39)
    				.addGroup(gl_DangKyCoSoVatChatPanel.createParallelGroup(Alignment.BASELINE)
    					.addComponent(soLuongXoaJlb, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
    					.addComponent(soLuongXoaJtf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    				.addContainerGap(50, Short.MAX_VALUE))
    	);
    	
    	DangKyCoSoVatChatPanel.setLayout(gl_DangKyCoSoVatChatPanel);
    	pack();
    }// </editor-fold>//GEN-END:initComponents
    private void xoaCoSoVatChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
    	if(validateValueInForm()) {
    		
            try {
            	CoSoVatChatService coSoVatChatService = new CoSoVatChatService();
            	coSoVatChatService.themSoLuongCoSoVatChat(tenCoSoVatChatDetail.getText(),  Integer.parseInt(soLuongXoaJtf.getText()));
                    JOptionPane.showMessageDialog(null, "Thêm thành công!!");
                    close();
                    parentController.refreshData();
              
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
    	}
    }
    // check cac gia tri duoc nhap vao form
    private boolean validateValueInForm() {
        // check null
    	if(soLuongXoaJtf.getText().trim().isEmpty() 
    			
    			) {
            return false;
    	}
    	try {
    		int soLuong = Integer.parseInt(soLuongXoaJtf.getText());
    		if(soLuong <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng số lượng", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
    		}
    		if(soLuong > Integer.parseInt(soLuongTrongKhoDetail.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng còn lại trong kho nhỏ hơn " + soLuong, "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
    		}
    	} catch (Exception e) {
			// TODO: handle exception
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng số lượng", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
		}
    	
        return true;
    }
	private CoSoVatChatPanelController parentController;
    private JFrame parentFrame;
    private CoSoVatChatBean coSoVatChatBean;
    private AddNewController controller;
    private JPanel DangKyCoSoVatChatPanel;
    private JTextField soLuongXoaJtf;
    private JLabel tenCoSoVatChatDetail;
    private JLabel tongSoLuongDetail;
    private JLabel soLuongMuonDetail;
    private JLabel soLuongTrongKhoDetail;
}
