package views.CoSoVatChatFrame;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import controllers.CoSoVatChatPanelController;
import controllers.CoSoVatChatController.XemChiTietCoSoVatChatCotroller;
import services.CoSoVatChatService;
import views.MuonTraFrame.DangKySuDungFrame;
import views.MuonTraFrame.MuonCoSoVatChatPhongBanFrame;
import models.CoSoVatChatModel;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import Bean.CoSoVatChatBean;

import javax.swing.JScrollPane;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.JPanel;
import java.awt.Color;

public class XemChiTietCoSoVatChatFrame extends javax.swing.JFrame {
    private XemChiTietCoSoVatChatCotroller controller;
    private CoSoVatChatPanelController parentController;
    private JFrame parentJFrame;
    
    /**
     * Creates new form ChuyenDiNoiKhac
     */
    public XemChiTietCoSoVatChatFrame(CoSoVatChatPanelController parentController, JFrame parentJFrame, String tenCoSoVatChatDetail, String tongSoLuong, String soLuongMuon, String soLuongTrongKho) {
        this.parentController = parentController;
        this.parentJFrame = parentJFrame;
        this.parentJFrame.setEnabled(false);
    	initComponents();
    	this.tenCoSoVatChatDetail.setText(tenCoSoVatChatDetail);
    	this.tongSoLuongDetail.setText(tongSoLuong);
    	this.soLuongMuonDetail.setText(soLuongMuon);
    	this.soLuongTrongKhoDetail.setText(soLuongTrongKho);
        pack();
        controller = new XemChiTietCoSoVatChatCotroller(this.tablePanel, this.tenCoSoVatChatDetail);
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 566, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 211, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        controller.setDataTable();
    	setIconImage(Toolkit.getDefaultToolkit().getImage(DangKySuDungFrame.class.getResource("/Icons/house.png")));
    	setTitle("Xem chi tiết cơ sở vật chất");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xemChiTietPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        xemChiTietPanel.setBackground(new Color(255, 228, 228));
        
        JLabel tenCoSoVatChatJlb = new JLabel("Tên cơ sở vật chất:");
        tenCoSoVatChatJlb.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        tenCoSoVatChatDetail = new JLabel("null");
        tenCoSoVatChatDetail.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        tongSoLuongDetail = new JLabel("null");
        tongSoLuongDetail.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        JLabel tongSoLuongJlb = new JLabel("Tổng số lượng:");
        tongSoLuongJlb.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        JLabel soLuongMuonJlb = new JLabel("Số lượng mượn:");
        soLuongMuonJlb.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        soLuongMuonDetail = new JLabel("null");
        soLuongMuonDetail.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        JLabel soLuongTrongKhoJlb = new JLabel("Số lượng trong kho:");
        soLuongTrongKhoJlb.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        soLuongTrongKhoDetail = new JLabel("null");
        soLuongTrongKhoDetail.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        JLabel lblNhTiTr = new JLabel("");
        lblNhTiTr.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        nhaTaiTroDetail = new JLabel("");
        nhaTaiTroDetail.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        JLabel bangDanhSachNguoiMuonJlb = new JLabel("Bảng danh sách người mượn");
        bangDanhSachNguoiMuonJlb.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        tablePanel = new JPanel();
        tablePanel.setAutoscrolls(true);

        javax.swing.GroupLayout gl_xemChiTietPanel = new javax.swing.GroupLayout(xemChiTietPanel);
        gl_xemChiTietPanel.setHorizontalGroup(
        	gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        				.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        				.addComponent(bangDanhSachNguoiMuonJlb, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        					.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        							.addComponent(tenCoSoVatChatJlb, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(tenCoSoVatChatDetail, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        							.addComponent(tongSoLuongJlb, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(tongSoLuongDetail, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        							.addComponent(lblNhTiTr, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
        							.addGap(6)
        							.addComponent(nhaTaiTroDetail, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        							.addComponent(soLuongMuonJlb, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(soLuongMuonDetail, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        							.addGap(141)
        							.addComponent(soLuongTrongKhoJlb, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(soLuongTrongKhoDetail, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap())
        );
        gl_xemChiTietPanel.setVerticalGroup(
        	gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_xemChiTietPanel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.BASELINE)
        					.addComponent(tenCoSoVatChatJlb)
        					.addComponent(tenCoSoVatChatDetail))
        				.addComponent(lblNhTiTr, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nhaTaiTroDetail, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.LEADING)
        				.addComponent(soLuongTrongKhoJlb, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.BASELINE)
        					.addComponent(soLuongMuonDetail, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addComponent(soLuongMuonJlb, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        				.addComponent(soLuongTrongKhoDetail, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_xemChiTietPanel.createParallelGroup(Alignment.BASELINE)
        					.addComponent(tongSoLuongJlb, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addComponent(tongSoLuongDetail, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)))
        			.addGap(32)
        			.addComponent(bangDanhSachNguoiMuonJlb)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        			.addContainerGap())
        );
        xemChiTietPanel.setLayout(gl_xemChiTietPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(xemChiTietPanel, GroupLayout.PREFERRED_SIZE, 877, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(xemChiTietPanel, GroupLayout.PREFERRED_SIZE, 407, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

    }// </editor-fold>//GEN-END:initComponents
    private CoSoVatChatBean coSoVatChatBean;
    private CoSoVatChatModel coSoVatChatModel;
    private CoSoVatChatService coSoVatChatService;
    private javax.swing.JPanel xemChiTietPanel;
    private JPanel tablePanel;
    private JLabel tongSoLuongDetail;
    private JLabel tenCoSoVatChatDetail;
    private JLabel nhaTaiTroDetail;
    private JLabel soLuongMuonDetail;
    private JLabel soLuongTrongKhoDetail;
}
